exclude:
  - 'vendor/bundle/**/*'
  - 'spec/**/*'

linters:

  LineLength:
    max: 120

  RuboCop:
    ignored_cops:
      - Layout/EmptyLineAfterGuardClause
      - Layout/SpaceInsideHashLiteralBraces
      - Lint/Void
      - Metrics/BlockLength
      - Layout/LineLength
      - Style/TernaryParentheses
      - Layout/TrailingEmptyLines
      - Layout/LineLength

  SpaceInsideHashAttributes:
    enabled: false

  ViewLength:
    enabled: false

  IdNames:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false
