require:
  - rubocop-performance
  - rubocop-rails

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - db/schema.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20

Layout/CommentIndentation:
  Exclude:
    - 'Gemfile'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'config/puma.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/devise.rb
    - db/schema.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAfterComma:
  Exclude:
    - 'config/puma.rb'

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'config/puma.rb'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
