services:

  #
  # メインコンテナ
  #
  web:
    build: .
    image: sliar-web:3.3.8

    volumes:
      - .:/app:cached
      - ./vendor/bundle/3.3:/usr/local/bundle:cached
    ports:
      - "3500:3500"
    environment:
      - PORT=3500

    links:
      - mysql

    command: bundle exec puma -C config/puma.rb

  #
  # MySQLのコンテナ
  #
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql:cached
      - "./my.cnf:/etc/mysql/conf.d/chset.cnf"
    ports:
      - "3306:3306"
