version: "3"

services:

  #
  # メインコンテナ
  #
  web:
    build:
      context: .

    volumes:
      - .:/app:cached
    ports:
      - "3500:3500"
    environment:
      - PORT=3500

    links:
      - mysql

    command: puma -C config/puma.rb

  #
  # MySQLのコンテナ
  #
  mysql:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql:cached
      - "./my.cnf:/etc/mysql/conf.d/chset.cnf"
