name: Brakeman

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/ruby-common-setup
        with:
          runner-os: ubuntu-latest

      - uses: steiley/exec-ruby-diagnostic@v1.0.1
        with:
          gem_name: brakeman
