name: rails_best_practices

on:
  pull_request:
    branches:
    - master

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: masa-iwasaki/setup-rbenv@v1

      - name: Cache RBENV_ROOT
        uses: actions/cache@v1
        id: cache_rbenv
        with:
          path: /home/runner/.rbenv
          key: ${{ runner.os }}-rbenv-${{ hashFiles('**/.ruby-version') }}
          restore-keys: |
            {{ runner.os }}-rbenv-

      - name: Install Ruby
        run: |
          eval "$(rbenv init -)"
          rbenv install -s `cat .ruby-version`

      - uses: steiley/exec-ruby-diagnostic@v1.0.4
        with:
          gem_name: rails_best_practices
