name: RSpec

on:
  pull_request:
    branches:
    - master

jobs:

  execute:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root

    container:
      image: cimg/ruby:3.4.4-node
      options: --user root

    steps:
    - uses: actions/checkout@master

    - name: Build and setup
      run: |
        cp config/database.yml.sample config/database.yml
        gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
        bundle config build.nokogiri --use-system-libraries
        bundle install --jobs 4 --retry 3

    - name: Database setup
      env:
        HOGE: ${{ secrets.HOGE }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:schema:load --trace RAILS_ENV=test

    - name: Exec rspec
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: bundle exec rspec
