name: Rubocop

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: clupprich/ruby-build-action@master
      id: rubocop
      with:
        ruby-version: 2.6.5
    - name: Install and execute Rubocop
      run: |
        gem i rubocop
        gem i rubocop-performance
        gem i rubocop-rails
        rubocop
