name: Rubocop

on:
  pull_request:
    branches:
    - master

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler: 'none'
    - uses: steiley/exec-ruby-diagnostic@v1.0.7
      with:
        gem_name: rubocop
